# Generated by Django 2.1.7 on 2019-03-21 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innotech', '0004_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
