# Generated by Django 2.1.7 on 2019-03-21 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innotech', '0005_auto_20190321_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='summary',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
